### ISSUE TITLE
Plugin name capitalization

### ISSUE THREAD

**Issue by phinjensen** [dayjs/dayjs-website#10]
Ive noticed while going through the documentation for Day.js that plugins seem to follow camelCase with the initial letter lowercase, such as `localizedFormat`. However, in the documentation table of contents, the list of Plugins all start with an uppercase letter, and in other places in the documentation (such as https://github.com/dayjs/dayjs-website/blob/master/docs/display/format.md), the first letter is capitalized, which is a bit confusing. Should these be changed so the first letter is always lowercase, regardless of where it is in the documentation?

**Comment by iamkun** [comment]
To me, the first letter is capitalized is the plugin's name.

and the other one is the code.

Do you think this is confused or not?

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this
