### ISSUE TITLE
Abbreviated named offset for timezone i.e "z" (small z) is not working.

### ISSUE THREAD

**Issue by pravar-anu** [dayjs/dayjs-website#124]
In the advance Formatting options the small 'z' is used to show the "Abbriviated named offset" like - IST for Indian Standard Time. But, this is not working.

![Screenshot from 2023-12-13 13-28-49](https://github.com/dayjs/dayjs-website/assets/151901461/1a7bb8d1-d374-4e9b-8141-2aa89362db78)

Also adding the codesandbox : https://codesandbox.io/s/thirsty-lamport-d8q96x?file=/src/App.js

**Comment by ritik3236** [comment]
why closed?

**Comment by pravar-anu** [comment]
> why closed?

Because I made raised the issue in wrong place.
I made it to actual place : https://github.com/iamkun/dayjs/issues/2528
