### ISSUE TITLE
"isValid" returns true on invalid date.

### ISSUE THREAD

**Issue by Cerceis** [dayjs/dayjs-website#46]
```
        const testDate = "2021-07-07"
        console.log(dayjs(testDate).isValid())
        //Output : true
        const testDate = "abc07-07"
        console.log(dayjs(testDate).isValid())
        //Output : false
        const testDate = "abc-07-07"
        console.log(dayjs(testDate).isValid())
        //Output : true <-- Problem
```
Or does it intended to only check for the date format ?

**Comment by iamkun** [comment]
isValid only checks if it's a valid date to Date object. 


You may specify a boolean for the last argument to use strict parsing. Strict parsing requires that the format and input match exactly, including delimiters.
https://day.js.org/docs/en/parse/string-format
