### ISSUE TITLE
preParsePostFormat documentation is missing

### ISSUE THREAD

**Issue by HELWATANY** [dayjs/dayjs-website#60]
After merging pull request [#1255](https://github.com/iamkun/dayjs/pull/1255) to solve issue [#416](https://github.com/iamkun/dayjs/issues/416) on the main repo, the website documentation is missing `preParsePostFormat` plugin documentation.

The plugin needs to be loaded in order to transform language numerals such as `ar` displaying "[Eastern Arabic numerals](https://en.wikipedia.org/wiki/Eastern_Arabic_numerals)" `۰۱۲۳۴۵۶۷۸۹` instead of "[Arabic numerals](https://en.wikipedia.org/wiki/Arabic_numerals)" `0123456789`.

**Comment by iamkun** [comment]
Interested to submit a pull request?

**Comment by HELWATANY** [comment]
Sure will do 😃

**Comment by VehpuS** [comment]
Already done (just noticed the issue). https://day.js.org/docs/en/plugin/preparse-postformat

**Comment by iamkun** [comment]
done
