### ISSUE TITLE
[Feature Request] add dayjs script in doc website

### ISSUE THREAD

**Issue by lqzhgood** [dayjs/dayjs-website#84]
add  `<script src="https://unpkg.com/dayjs/dayjs.min.js"></script>`  in doc website can helpful quick validation `dayjs` in browser `F12`

I find position in https://github.com/dayjs/dayjs-website/blob/8336b896f5584f161ac99ed502ede6ad21bc74f6/website/siteConfig.js#L85

but have a quick way  to load **all** plugin in the browser ?

**Comment by iamkun** [comment]
yes, dayjs is available in the console already

**Comment by lqzhgood** [comment]
3Q~
